# Generated by Django 3.0.1 on 2020-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('food', 'FOOD'), ('technical', 'TECHNICAL'), ('technology', 'TECHNOLOGY'), ('news', 'NEWS'), ('movies', 'MOVIES'), ('games', 'GAMES'), ('social', 'SOCIAL'), ('economy', 'ECONOMY'), ('business', 'BUSINESS'), ('others', 'OTHERS')], default='select', max_length=11),
        ),
    ]
