# Generated by Django 3.0.1 on 2020-10-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201010_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
