# Generated by Django 3.0.1 on 2020-09-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20200930_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='views',
        ),
    ]
