# Generated by Django 3.0.1 on 2020-10-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20201001_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='post_id',
            new_name='notes_id',
        ),
    ]
