# Generated by Django 3.0.1 on 2020-10-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20201001_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notes_id',
        ),
        migrations.AddField(
            model_name='task',
            name='myid',
            field=models.AutoField(default='170', primary_key=True, serialize=False),
        ),
    ]
