# Generated by Django 3.0.1 on 2020-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20201001_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='myid',
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, default='default=1770', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
