# Generated by Django 3.0.1 on 2020-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20201002_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
