# Generated by Django 3.0.1 on 2020-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='add',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
