# Generated by Django 3.0.1 on 2020-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200924_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
