# Generated by Django 3.0.1 on 2020-10-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_verifyemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
