# Generated by Django 3.0.1 on 2020-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('food', 'FOOD'), ('technical', 'TECHNICAL'), ('technology', 'TECHNOLOGY'), ('news', 'NEWS'), ('movies', 'MOVIES'), ('games', 'GAMES'), ('social', 'SOCIAL'), ('economy', 'ECONOMY'), ('business', 'BUSINESS'), ('others', 'OTHERS')], default='select', max_length=11)),
            ],
        ),
    ]
