# Generated by Django 3.0.1 on 2020-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Category',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='BUSINESS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ECONOMY',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='FOOD',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='GAMES',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='MOVIES',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='NEWS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='OTHERS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='SOCIAL',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='TECHNICAL',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='TECHNOLOGY',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
