# Generated by Django 3.0.1 on 2020-10-10 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_usermodel_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='Preference',
        ),
    ]
