# Generated by Django 3.0.1 on 2020-10-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20201010_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyemail',
            name='customer',
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
