# Generated by Django 3.0.1 on 2020-10-12 14:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20201010_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='FITNESS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='HISTORY',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='KNOWLEDGE',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
