# Generated by Django 3.0.1 on 2020-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200927_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.CharField(default=True, max_length=2000000),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
