# Generated by Django 3.0.1 on 2020-09-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200929_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='private',
        ),
    ]
