# Generated by Django 3.0.1 on 2020-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_task_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='VisibilityMode',
            field=models.CharField(choices=[('Pub', 'Public'), ('Pri', 'Private')], default='Pub', max_length=128),
        ),
    ]
