# Generated by Django 3.0.1 on 2020-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_task_visibilitymode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.CharField(auto_created=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
