# Generated by Django 3.0.1 on 2020-10-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20201002_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Category',
            field=models.CharField(choices=[('food', 'FOOD'), ('technical', 'TECHNICAL'), ('technology', 'TECHNOLOGY'), ('news', 'NEWS'), ('movies', 'MOVIES'), ('games', 'GAMES'), ('social', 'SOCIAL'), ('economy', 'ECONOMY'), ('business', 'BUSINESS'), ('others', 'OTHERS')], default='select', max_length=11),
        ),
    ]
